name: Docker Image Create CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        path: hackaton-oauth/hackaton-avengers
    - name: Build the Docker image
      run: docker build -t hackaton-oauth:$(date +%s) -f Dockerfile .
