name: Docker Image Create CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: Bhacaz/checkout-files@v2
        with:
          files: hackaton-oauth/hackaton-avengers
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./hackaton-oauth/hackaton-avengers
          file: ./hackaton-oauth.api/Dockerfile
          tags: hackaton-oauth:latest
          outputs: type=docker,dest=/tmp/hackaton-oauth.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: hackaton-oauth
          path: /tmp/hackaton-oauth.tar