name: Docker Image Create CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t hackaton-oauth -f hackaton-oauth/hackaton-avengers/Dockerfile ./hackaton-oauth/hackaton-avengers

      - name: Push Docker image
        run: docker push docker.pkg.github.com/${{ github.repository }}/IMAGE_NAME:${{ github.run_number }}